services:
  - type: web
    name: alunizaje-lunar
    env: python
    buildCommand: pip install -r requirements-prod.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
